"use client"
// import {Metadata} from 'next'
import Link from 'next/link'
import {useState, useEffect} from 'react'

// export const metadata = {
//     title: 'Posts | Churchnext',
//     description: 'Generated by create next app',
// }


  const Posts = () => {
    const [posts, setPosts] = useState([])

    const getData = async () => {
    await fetch('https://jsonplaceholder.typicode.com/posts')
        .then(res => res.json())
        .then(data => {
            console.log(data)
            setPosts(data)
        })
  }

    useEffect(() => {
        getData()
    }, [])

    return <>
    <h1>Posts</h1>
        <ul>
            {posts.map(post => (
                <li key={post.id}>
                   <Link href={`/posts/${post.id}`}>{post.title}</Link>
                </li>
            ))}
        </ul>
   </>
}

export default Posts