import { Metadata } from "next";

export const metadata = {
  title: "Media | Churchnext",
  description: "Generated by create next app",
};

const Media = () => {
  return (
    <>
      <h1>Media</h1>
      <p>Our media work</p>
    </>
  );
};
export default Media;
