import {Metadata} from 'next'

export const metadata = {
    title: 'Contries | Churchnext',
    description: 'Generated by create next app',
}

const Contries = () => {
    return <>   
     <h1>Contries</h1>
        <p>Contries where we have some work</p> 
   </>

}
export default Contries