import {Metadata} from 'next'

export const metadata = {
    title: 'About | Churchnext',
    description: 'Generated by create next app',
}

const About = () => {
    return <h1>About</h1>
}
export default About