import { Metadata } from "next";

export const metadata = {
  title: "Mission | Churchnext",
  description: "Generated by create next app",
};

const Mission = () => {
  return <h1>Mission</h1>;
};
export default Mission;
