import { Metadata } from "next";

export const metadata = {
  title: "Contacts | Churchnext",
  description: "Generated by create next app",
};

const Contacts = () => {
  return <h1>Contacts</h1>;
};
export default Contacts;
