import ContactsPage from '../../components/ContactsPage'
import { Metadata } from "next"

export const metadata = {
  title: "Contacts | Churchnext",
  description: "Generated by create next app",
}

const Contacts = () => {
  return (
    <>
      <ContactsPage />
    </>
  )
}
export default ContactsPage
