//"use client"

import {Metadata} from 'next'

export const generateMetadata = ({params: {id}}) => {
    return{
        title: `Post ${id}| Churchnext`,
        description: 'Generated by create next app',
    }
}


const Post = ({params: {id}}) => {
    return <h1>Post page {id}</h1>
}
export default Post